//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov_41
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoint
    {
        public PickUpPoint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int PickUpPointID { get; set; }
        public string PickUpPointIndex { get; set; }
        public string PickUpPointCity { get; set; }
        public string PickUpPointStreet { get; set; }
        public string PickUpPointHouse { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
