//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov_41
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductCost { get; set; }

        public int ProductCostInt {
            get {
                return Convert.ToInt32(this.ProductCost);
            }

            set; }
        public int ProductDiscountMax { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductImporter { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }

        public string ProductPhotoOptimize
        {
            get
            {
                if (this.ProductPhoto != null)
                    return ".\\Resources\\products\\" + this.ProductPhoto;

                return ".\\Resources\\default_image.png";
            }
            set;
        }

        public string ProductStatus { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
